title = "Kanban widget"

# Kanban options
[data]
table = "Kanban"            # The name of the table whose data are shown
category = "Status"         # The column referencing categories
title = "Task"              # The column containing a card’s title
editable = true             # Only for the title
order = "Priority"          # The column defining cards order
details = ["Details"]	      # List of columns whose content will be shown in the details
details_unfolded = false    # Whether to show the details by default; otherwise, they’ll appear on click
highlighted = "lightyellow" # Color of the selected card

[categories]
table = "Kanban_status"     # The name of the table containing categories’ definition
title = "Title"             # The column containing a category’s title
order = "Order"             # The column defining categories order
color = "Color"             # The column defining a category’s background color


#Only change below if you know what you’re doing.

# Grist options
[grist]
allowSelectBy = true
requiredAccess = "full"

# Widget options.
[widget]
entrypoint = "pug"     # Name of one of the codes below

[[widget.codes]]
name = "cfg"           # Must be unique
type = "toml"          # This will determine CodeMirror’s mode
file = "config.toml"   # Optional: file to load at widget creation

[[widget.codes]]
name = "pug"
type = "pug"
file = "widget/pug.pug"

[[widget.codes]]
name = "py"
type = "python"
file = "widget/py.pyj"
